<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SteelSeriesAssist.Sonar\SteelSeriesAssist.Sonar.csproj" />
    <ProjectReference Include="..\..\src\SteelSeriesAssist.Application\SteelSeriesAssist.Application.csproj" />
  </ItemGroup>
</Project>
